name: gmailer_full
channels:
  - defaults
dependencies:
  - python=3.6.8
  - pip=21.2.2
  - pip:
    - numpy==1.18.5
    - openpyxl==3.0.5
    - pandas==1.1.2
    - pyinstaller==4.0
    - PySide2==5.15.0
    - xlrd==1.2.0
